/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-120072-g11d1b71c31-20250703"
#endif /* AVUTIL_FFVERSION_H */
